### ISSUE TITLE
Site errors and doesn't load at all

### ISSUE THREAD

**Issue by Erdragh** [mensatt/frontend#26]
![image](https://github.com/mensatt/frontend/assets/29674493/93cab811-b35f-42f0-a9c8-6c6fbf7144ac)

**Comment by stormofice** [comment]
Hey, thanks for the report :)

I can't seem to replicate this issue currently.

Could you share some information about the operating system and device you are encountering it on?
Does it still occur when you use Firefox without extensions [(for example by starting in safe mode)](https://support.mozilla.org/en-US/kb/diagnose-firefox-issues-using-troubleshoot-mode?redirectslug=Safe+Mode&redirectlocale=en-US#w_how-to-start-firefox-in-troubleshoot-mode) / in another browser?

**Comment by Erdragh** [comment]
Seems to have resolved itself by waiting.
